# This is a basic workflow

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  #  For dependency build/release related pipeline code
  #  test:
  #    name: Analyze Android
  #    runs-on: macos-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v3
  #
  #      - uses: actions/setup-java@v3
  #        with:
  #          distribution: temurin
  #          java-version: 11
  #
  #      - name: Setup Gradle
  #        uses: gradle/gradle-build-action@v2
  #
  #      - name: Setup Android SDK
  #        uses: android-actions/setup-android@v2
  #
  #      - name: Assemble
  #        env:
  #          GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
  #          GITHUB_PACKAGE_ACCESS_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN_GITHUB }}
  #        run: |
  #          ./gradlew clean assembleRelease
  #      - name: Publish
  #        run: ./gradlew publish
  #        env:
  #          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
  #          PUBLISHER_USERNAME: ${{ secrets.PUBLISHER_USERNAME }}
  #          OWNER: ${{ secrets.OWNER }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: Run a one-line script
#        run: echo Hello, World! from activity

      - name: Build Step
        run: ./gradlew build
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test and deploy your project.

  lint:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
#      - name: Print the Lint
#        run: echo Lint

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
#      - name: Print the Unit Test case
#        run: echo Unit Test Case

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [ unit-test ]
    runs-on: macos-latest
    steps:
#      - name: Print the Instrumentation Test case
#        run: echo Instrumentation Test Case

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      #      - name: Setup Android SDK
      #        uses: android-actions/setup-android@v2

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          #          target: default
          arch: x86_64
          script: ./gradlew connectedCheck --stacktrace

      #      - name: Android Emulator Runner
      #        uses: ReactiveCircus/android-emulator-runner@v2.27.0
      #        with:
      #          api-level: 29
      #          target: default
      #          arch: x86
      #          profile: Nexus 6
      #          script: ./gradlew connectedCheck --stacktrace

      - name: Upload test-report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
