# This is a basic workflow

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/int-results-debug.html



  #  jobs:
  #    build:
  #      runs-on: ubuntu-latest
  #      steps:
  #        - uses: actions/checkout@v2
  #
  #        - name: Run a one-line script
  #          run: echo Hello, World! from activity
  #
  #        - name: Run a multi-line script
  #          run: |
  #            echo Add other actions to build,
  #            echo test and deploy your project.
